<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\Service\FlightInfo' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/Service/FlightInfo.php';

return $this->services['AppBundle\Service\FlightInfo'] = new \AppBundle\Service\FlightInfo('km', 'h');
