<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWx6nik7\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWx6nik7/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWx6nik7.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWx6nik7\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWx6nik7\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wx6nik7',
    'container.build_id' => '38fcafae',
    'container.build_time' => 1528011525,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWx6nik7');
