<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPzlx8ox\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPzlx8ox/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPzlx8ox.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPzlx8ox\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPzlx8ox\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pzlx8ox',
    'container.build_id' => 'c905c602',
    'container.build_time' => 1528115326,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPzlx8ox');
