<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYssln7c\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYssln7c/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYssln7c.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYssln7c\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYssln7c\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Yssln7c',
    'container.build_id' => '610026e0',
    'container.build_time' => 1528358042,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerYssln7c');
